In [268]:
import prestodb
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import mean_squared_error
import numpy as np


conn = prestodb.dbapi.connect(
       host='watsonxdata',
       port=8443,
       user='ibmlhadmin',
       catalog='hive_data',
       schema='ontime',
       http_scheme='https',
       auth=prestodb.auth.BasicAuthentication("ibmlhadmin", "password")
)
conn._http_session.verify = '/certs/lh-ssl-ts.crt'
cur = conn.cursor()
cur.execute("SELECT * FROM hive_data.ontime.ontime ")
rows = cur.fetchall()

In [269]:
subset= "SELECT dayofmonth, dot_id_reporting_airline, flight_number_reporting_airline,originairportid, destairportid, crsdeptime,deptime, depdelay,crsarrtime, arrtime, arrdelay,crselapsedtime, distance,carrierdelay,weatherdelay,nasdelay,securitydelay,lateaircraftdelay FROM hive_data.ontime.ontime LIMIT 200000 "
cur.execute(subset)
sub=cur.fetchall()
#delay="SELECT carrierdelay,weatherdelay,nasdelay,securitydelay,lateaircraftdelay FROM hive_data.ontime.ontime LIMIT 100"
reason="SELECT dayofmonth, dot_id_reporting_airline, flight_number_reporting_airline,originairportid, destairportid, crsdeptime,deptime,crsarrtime, arrtime,crselapsedtime, distance FROM hive_data.ontime.ontime LIMIT 200000 "
#cur.execute(delay)
#delays=cur.fetchall()
cur.execute(reason)
reasons=cur.fetchall()
df_sub = pd.DataFrame(sub)
#df_delays=pd.DataFrame(delays)
df_reasons=pd.DataFrame(reasons)
reasons_columns = ['DayOfMonth', 'DotIDReportingAirline', 'FlightNumberReportingAirline', 'OriginAirportID', 'DestAirportID', 'CRSDepTime', 'DepTime',  'CRSArrTime', 'ArrTime', 
                   'CRSElapsedTime', 'Distance']
df_reasons.columns=reasons_columns
#df_sub[0] = pd.to_datetime(df_sub[0])
#df_sub.set_index(0, inplace=True)

In [270]:
correlation_matrix = df_reasons.corrwith(df_sub.iloc[:, 14])
print('WEATHER')
correlation_matrix

WEATHER

DayOfMonth                      0.025503
DotIDReportingAirline           0.016223
FlightNumberReportingAirline    0.016269
OriginAirportID                 0.005072
DestAirportID                  -0.005364
CRSDepTime                     -0.000907
DepTime                         0.007814
CRSArrTime                     -0.000660
ArrTime                        -0.003369
CRSElapsedTime                 -0.009029
Distance                       -0.009495
dtype: float64

In [271]:
correlation_matrix = df_reasons.corrwith(df_sub.iloc[:, 17])
print('AIRCRAFT')
correlation_matrix

AIRCRAFT

DayOfMonth                      0.031068
DotIDReportingAirline           0.041862
FlightNumberReportingAirline    0.060874
OriginAirportID                -0.002936
DestAirportID                  -0.010518
CRSDepTime                      0.071636
DepTime                         0.114145
CRSArrTime                      0.064141
ArrTime                         0.054164
CRSElapsedTime                 -0.030253
Distance                       -0.029552
dtype: float64

In [272]:
correlation_matrix = df_reasons.corrwith(df_sub.iloc[:, 16])
print('SECURITY')
correlation_matrix

SECURITY

DayOfMonth                     -0.002844
DotIDReportingAirline          -0.001301
FlightNumberReportingAirline   -0.002952
OriginAirportID                 0.000990
DestAirportID                   0.003590
CRSDepTime                     -0.004007
DepTime                        -0.001582
CRSArrTime                     -0.003164
ArrTime                        -0.000517
CRSElapsedTime                  0.004867
Distance                        0.004369
dtype: float64

In [273]:
correlation_matrix = df_reasons.corrwith(df_sub.iloc[:, 15])
print('SYSTEM')
correlation_matrix

SYSTEM

DayOfMonth                      0.054545
DotIDReportingAirline           0.050476
FlightNumberReportingAirline    0.033983
OriginAirportID                -0.004780
DestAirportID                  -0.005621
CRSDepTime                      0.006919
DepTime                         0.032207
CRSArrTime                      0.010637
ArrTime                         0.029623
CRSElapsedTime                  0.005018
Distance                        0.000123
dtype: float64

In [274]:
correlation_matrix = df_reasons.corrwith(df_sub.iloc[:, 13])
print('CARRIER')
correlation_matrix

CARRIER

DayOfMonth                      0.004496
DotIDReportingAirline           0.025509
FlightNumberReportingAirline    0.025301
OriginAirportID                -0.014679
DestAirportID                  -0.005742
CRSDepTime                     -0.001035
DepTime                         0.040164
CRSArrTime                      0.000917
ArrTime                         0.018716
CRSElapsedTime                 -0.003116
Distance                       -0.005894
dtype: float64

In [275]:
correlation_matrix = df_reasons.corrwith(df_sub.iloc[:, 10])
print('ARRDELAY')
correlation_matrix

ARRDELAY

DayOfMonth                      0.045791
DotIDReportingAirline           0.051752
FlightNumberReportingAirline    0.067778
OriginAirportID                -0.007894
DestAirportID                  -0.013143
CRSDepTime                      0.047260
DepTime                         0.101426
CRSArrTime                      0.043643
ArrTime                         0.052324
CRSElapsedTime                 -0.038990
Distance                       -0.037441
dtype: float64

In [276]:
correlation_matrix = df_reasons.corrwith(df_sub.iloc[:, 7])
print('depDELAY')
correlation_matrix

depDELAY

DayOfMonth                      0.027941
DotIDReportingAirline           0.023989
FlightNumberReportingAirline    0.051226
OriginAirportID                -0.014892
DestAirportID                  -0.007914
CRSDepTime                      0.056986
DepTime                         0.118395
CRSArrTime                      0.056394
ArrTime                         0.060264
CRSElapsedTime                 -0.008019
Distance                       -0.009650
dtype: float64

In [277]:
#df_sub[0] = pd.to_datetime(df_sub[0])
df_sub.set_index(0, inplace=True)
df_sub.sort_index(inplace=True)
df_sub

,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17
0,,,,,,,,,,,,,,,,,
1,19805,1904,12266,11298,1130,1127,-3,1240,1228,-12,70,224,0,0,0,0,0
1,19805,1240,11298,13487,2110,2118,8,2320,2326,6,130,852,0,0,0,0,0
1,19805,1383,13303,12266,720,717,-3,920,854,-26,180,964,0,0,0,0,0
1,19790,1330,11433,11057,1402,1357,-5,1557,1558,1,115,500,0,0,0,0,0
1,19790,1330,11057,11433,1645,1642,-3,1844,1825,-19,119,500,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
31,19393,417,13891,12889,1320,1339,19,1415,1433,18,55,197,0,0,0,0,18
31,20355,1460,11057,12478,1810,2012,122,2000,2151,111,110,541,0,0,0,0,111
31,20355,1461,14100,11278,1730,1756,26,1821,1843,22,51,119,22,0,0,0,0
31,20363,3341,11298,13487,1821,1906,45,2049,2123,34,148,852,4,0,0,0,30
31,20366,5052,10397,13795,2125,2118,-7,2244,2230,-14,79,399,0,0,0,0,0

In [278]:
average_delay = df_sub[10][:].mean()
df_sub['TargetDelay'] = average_delay
average_delay

3.0992

In [279]:
from sklearn.model_selection import train_test_split
from sklearn.neural_network import MLPRegressor
from sklearn.metrics import mean_squared_error

X=df_reasons
y=df_sub[10][:]
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [280]:
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [288]:
model = MLPRegressor(hidden_layer_sizes=(100,150), activation='relu', solver='adam', learning_rate_init=0.01, random_state=42)
model.fit(X_train_scaled, y_train)

y_pred = model.predict(X_test_scaled)
mse = mean_squared_error(y_test, y_pred)
print(f'Mean Squared Error on Test Set: {mse}')

/usr/local/lib64/python3.9/site-packages/sklearn/neural_network/_multilayer_perceptron.py:698: UserWarning: Training interrupted by user.
  warnings.warn("Training interrupted by user.")

Mean Squared Error on Test Set: 1339.356893925821

In [287]:
#new_predictions = model.predict(new_data)

In [239]:
#Predicted delays for the flights with destination the airport of chicago
query="SELECT dayofmonth, dot_id_reporting_airline, flight_number_reporting_airline,originairportid, destairportid, crsdeptime,deptime,crsarrtime, arrtime,crselapsedtime, distance FROM hive_data.ontime.ontime WHERE dest='ORD' LIMIT 10000 "

cur = conn.cursor()
cur.execute(query)
results = cur.fetchall()

columns = ['dayofmonth', 'dot_id_reporting_airline', 'flight_number_reporting_airline','originairportid', 'destairportid', 'crsdeptime','deptime','crsarrtime', 'arrtime','crselapsedtime', 'distance' ]
df_ORD = pd.DataFrame(results, columns=columns)
X_ORD=df_ORD
X_ORD_scaled=scaler.fit_transform(df_ORD)
predicted_delays_ORD=model.predict(X_ORD_scaled)
df_ORD['predicted_delays']=predicted_delays_ORD

In [240]:
df_ORD

,dayofmonth,dot_id_reporting_airline,flight_number_reporting_airline,originairportid,destairportid,crsdeptime,deptime,crsarrtime,arrtime,crselapsedtime,distance,predicted_delays
0,1,20363,3338,12478,13930,1540,1546,1748,1753,188,740,-0.550697
1,2,20363,3429,14869,13930,1115,1111,1527,1530,192,1250,0.750962
2,3,20363,3650,11193,13930,1612,1610,1631,1620,79,265,-3.901326
3,4,20363,3650,11193,13930,1612,1604,1631,1622,79,265,-4.544143
4,26,20363,3523,12478,13930,1540,1554,1742,1803,182,740,4.011395
...,...,...,...,...,...,...,...,...,...,...,...,...
9995,9,19977,214,14771,13930,2238,2236,442,423,244,1846,-13.918252
9996,9,19977,215,14771,13930,1819,1803,25,2351,246,1846,-9.327296
9997,7,19977,1003,12892,13930,600,626,1201,1228,241,1745,10.794455
9998,6,19977,162,11278,13930,716,724,826,830,130,612,5.338905
9999,8,19977,305,14107,13930,740,736,1156,1154,196,1440,3.295842